# Generated by Django 5.0.2 on 2024-03-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('academicLevel', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('fieldStudy', models.CharField(max_length=100)),
                ('studyDestination', models.CharField(max_length=100)),
                ('enrollment', models.CharField(max_length=100)),
                ('languageProficiency', models.CharField(max_length=100)),
            ],
        ),
    ]
